### ISSUE TITLE
can't find associated bill and topic for each speech

### ISSUE THREAD

**Issue by negar-mokhberian** [awebson/congressional_adversary#1]
Hi,
Thanks for publishing this amazing pipeline. I am interested in finding the associated bill and topic for each speech.
I can see that you are assigning speech.bill in [search_bill_mentions.py](https://github.com/awebson/congressional_adversary/blob/68dbfcda1d30a9300453f2010f1e1581bbc31f3e/src/preprocess_CR/search_bill_mentions.py) but it seems like I need to have access to the file '../../data/interim/titles_and_summaries_all_cleaned.txt' which I couldn't find in your repo or the original congress speeches dataset. I would really appreciate it if you could share this file. 

Thanks

**Comment by awebson** [comment]
Whoops sorry about that omission and thanks for letting us know! I just uploaded the scraped bill data which you can now download from [here](https://drive.google.com/file/d/1ub9eForMf-Rr3IncqA5yQ3sOnL9owQzX/view?usp=sharing).

**Comment by negar-mokhberian** [comment]
Thank you for your prompt response. The file helped a lot!
